version: '3.9'

services:
  mongo:
    command: mongod --quiet --logpath /var/log/mongodb/mongodb.log
    ports:
      - 27017:27017
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
  api:
      environment:
        DEVELOPMENT: true
      volumes:
        - ./:/~/zhomemedia