version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: zHomeMedia
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
  redis:
    image: "redis:alpine"
  api:
    build: .
    image: zhomemedia
    environment:
      DEVELOPMENT: false
      MONGO_HOST: mongo
      REDIS_SERVER: redis
      STORAGE: /storage
    volumes:
      - ${STORAGE}:/storage
    command: yarn start
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
      - redis