version: '3.9'

services:
  mongo:
    command: mongod --quiet --logpath /var/log/mongodb/mongodb.log
    ports:
      - 27017:27017
  api:
      environment:
        DEVELOPMENT: true
      volumes:
        - ./:/~/zhomemedia
  api-tests:
    build: .
    image: zhomemedia
    environment:
      DEVELOPMENT: true
      MONGO_HOST: mongo
      REDIS_SERVER: redis
    command: dockerize
        -wait tcp://mongo:27017 -wait tcp://redis:6379 -timeout 10s
        sh -c "yarn test"
    depends_on:
      - mongo
      - redis