version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: zHomeMedia
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
  redis:
    image: "redis:alpine"
  api:
    build: .
    image: zhomemedia-api
    environment:
      DEVELOPMENT: false
      MONGO_HOST: mongo
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      REDIS_SERVER: redis
      STORAGE: /storage
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ${STORAGE}:/storage
    command: yarn start
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
      - redis
  api-tests:
    build: .
    image: zhomemedia-api
    environment:
      DEVELOPMENT: true
      MONGO_HOST: mongo
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      REDIS_SERVER: redis
      STORAGE: /storage
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./coverage:/~/zhomemedia/coverage
    command: dockerize
        -wait tcp://mongo:27017 -wait tcp://redis:6379 -timeout 10s
        sh -c "yarn test"
    depends_on:
      - mongo
      - redis