# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
       - image: cimg/base:2022.07
    steps:
      - checkout
      - run: sudo apt-get update
      - setup_remote_docker:
          version: 20.10.14
      - run: |
            docker-compose up --build --abort-on-container-exit