# .circleci/config.yml
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: |
            docker-compose up --build --abort-on-container-exit api-tests