# .circleci/config.yml
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3
jobs:
  build:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: |
            docker-compose up --build --abort-on-container-exit api-tests
      - codecov/upload:
          file: coverage/coverage-final.json
workflows:
  build-test:
    jobs:
      - build